name: Check

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
name: Debugging
      run: |
        pwd
        ls -la

      - name: Build the project
        run: ./gradlew jar
      
      - name: Run all automated tests
        run: ./gradlew check
