name: Check

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

        - run:
      name: chmod permissions
      command: chmod +x ./gradlew

      - name: Build the project
        run: ./gradlew jar
      
      - name: Run all automated tests
        run: ./gradlew check
